version: '3'

services:

  #Database
  ny-cab-data:
    build: ./ny-cab-data
    container_name: ny-cab-data
    restart: always
    environment:
      MYSQL_DATABASE: ny_cab_data
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ny-cab-db:/var/lib/mysql
  
  #DB-API
  ny-cab-db-api:    
    build:
      context: ./ny-cab-api
      dockerfile: ./ny-cab-db-api/Dockerfile
    restart: on-failure
    ports:
      - '7001:7001'
    depends_on: 
      - ny-cab-data 
    environment:
      MYSQL_HOST: ny-cab-data
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}

  #WEB-API
  ny-cab-web-api:    
    build:
      context: ./ny-cab-api
      dockerfile: ./ny-cab-web-api/Dockerfile
    restart: on-failure
    ports:
      - '7002:7002'
    depends_on: 
      - ny-cab-data 
      - ny-cab-db-api
    environment:
       WAIT_HOSTS: ny-cab-data:3306, ny-cab-db-api:7001
       DB_API_URL: http://ny-cab-db-api:7001

volumes:
  ny-cab-db:
